version: '3.9'

services:
  node:
    build: .
    container_name: helloworld
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: 
      "node index.js"